// Code generated by "stringer -type=SkillType"; DO NOT EDIT

package main

import "fmt"

const _SkillType_name = "fluentproficientcompetentfamiliar"

var _SkillType_index = [...]uint8{0, 6, 16, 25, 33}

func (i SkillType) String() string {
	if i < 0 || i >= SkillType(len(_SkillType_index)-1) {
		return fmt.Sprintf("SkillType(%d)", i)
	}
	return _SkillType_name[_SkillType_index[i]:_SkillType_index[i+1]]
}
